### ISSUE TITLE
判断是否已注册 永远返回false

### ISSUE THREAD

**Issue by daiwenbo88** [wind0ws/rxbus2#2]
RxBus.getDefault().isRegistered(this) 永远返回false

**Comment by wind0ws** [comment]
首先要澄清一点，```RxBus.getDefault().register(this);``` 是个异步注册监听事件的过程。
这就意味着你不能在刚执行完 ```RxBus.getDefault().register(this);```  这个方法后立即用 ``` RxBus.getDefault().isRegistered(this) ```来判断有没有注册成功。  

通常来说，在执行这个```RxBus.getDefault().register(this);```注册的过程中，如果失败了会抛出异常的。
那么可能有的人要问了，那我怎么判断有没有注册成功呢，目前没有提供注册完所有注解方法事件的回调，后期如果真的有这样的需求，我会酌情考虑加入注册完事件的回调。

最后再回答你的问题，```RxBus.getDefault().isRegistered(this);```并 **不是** 永远返回false的.
你可以这样做个试验，在Activity的```onCreate()```中调用```RxBus.getDefault().register(this); ```来注册事件（当然你的Activity里要有带注解的监听事件方法），然后在Activity页面中放置一个Button，Button的点击事件就是简单的Toast出这个Activity是否已经注册，当你打开这个Activity后，你去点击这个Button，带有```true```的toast将显示在你的屏幕上。
